version: "3.7"
services:
  tact-api:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0.12
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
